### ISSUE TITLE
Python script exiting Device not found, or disconnected. Exiting

### ISSUE THREAD

**Issue by tojoleon** [alex-ong/powermate-win10#1]
Hi Alex,

Thank you for the support for the griffin Powermate. I had followed the instructions and installed WinUSB (v6.1.7600.16385) and the Powermate is being detected under hardware devices. Setup.py installed properly but powermate.py keeps exiting with device not found.
 Any ideas what could be causing this? I am using Windows 10 Pro 64Bit. 

The Powermate is working fine under the default driver and I am being able to configure using the default program. My issue is that the Powermate stops working when other applications are in forefront.

**Comment by alex-ong** [comment]
Hi,

thanks for being a guinea pig!

Are you sure that the VID and PID match?

when you use ZaDig, note down the VID and PID.

![image](https://user-images.githubusercontent.com/6406312/61687250-4e642980-ad65-11e9-8d21-40a0f58b3eea.png)

Edit powermate.py and check what it has as VID and PID.
In this case I have `VID = 077d, PID = 0410`
Apart from that, i'm not sure, since every other bit of code is a library call to other people's libraries. Let me know how you go!

Are you familiar with Python or are you a non-dev? Another problem could be using python3 instead of 2, or a problem when you installed winusbpy - note down if it actually installed correctly.

Also; i wrote this precisely because powermate stops working when other applications are in the forefront. I'm happily playing emulators with this powermate workaround.

I've also updated the powermate.py to print out all vid/pid pairs connected to your computer in the case of a failure.

**Comment by m00nlygreat** [comment]
Hi, same here

I checked VID and PID and they were fine, using python 2.7

winusbpy seems installed properly when I see the result of typing "winusbpy" on python prompt

```
>>>from winusbpy import *
>>> winusbpy
<module 'winusbpy.winusbpy' from 'C:\Python27\lib\site-packages\winusbpy\winusbpy.pyc'>
```

**Comment by alex-ong** [comment]
Hmm not sure, I dont have the device with me but it was working on my dev machine when i made this originally. I must have something installed that you guys dont. I don't have the device with me but i'll try and investigate the next time i can get my hands on it. Otherwise I'm deeply sorry, i know there are 2-3 of these repos for powermate floating around and the other ones didnt work which is why i wrote my own.

**Comment by fito-moonhyung** [comment]
Hmm. thanks for the reply! the only thing I want to know is how to make it work just like before with the official powermate app. Have any idea? or i need to reinstall windows .. 😂

**Comment by m00nlygreat** [comment]
Hmm. thanks for the reply! the only thing I want to know is how to make it work just like before with the official powermate app. Have any idea? or i need to reinstall windows .. 😂

**Comment by alex-ong** [comment]
@m00nlygreat try using https://www.nirsoft.net/utils/usb_devices_view.html
You should be able to uninstall all the relevant devices (note that unplugging a device in windows doesnt uninstall it; use this tool to do that), then uninstall WinUSB, then when plugging in the device again start as if you had the powermate from scratch. Let me know how that goes

**Comment by johnsawan79** [comment]
dear alex,

thanks for response, i'll check it out.

regards,
john sawan

**Comment by alex-ong** [comment]
Just tested this on a different computer. works fine. Any more issues let me know and i'll try and debug it !

**Comment by alex-ong** [comment]
@m00nlygreat 

# Uninstalling / Reverting (oh no, it doesnt work :( )
* Open Device manager
* Select Griffin power mate
* Update driver
* Choose from drivers
* Try each of the different drivers (the one that worked for me wasn't called Griffin Powermate, it was called "USB Input Device")
* ![image](https://user-images.githubusercontent.com/6406312/124419461-e1ef6300-dda0-11eb-935f-0237e921f3ce.png)
* Open Griffin powermate official software again, it should work with one of the drivers

I've also found another repo that *does* work for someone else, i'll link that in README.md
